# version: '3.8'
# services:
#   web:
#     image: nginx:alpine
#     ports:
#       - "8080:80"
  
#   app:
#     image: node:20-alpine
#     working_dir: /app
#     volumes: 
#       - ./:/app
#     command: node -e "setInterval(() => console.log('app running'),2000)"


# exercice3



services:
  app:
    image: node:20-alpine
    container_name: node_app
    working_dir: /app
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
       DB_HOST: db
       DB_PORT: 5432
       DB_USER: postgres
       DB_PASSWORD: ${DB_PASSWORD}
       DB_NAME: postgres
    command: sh -c "npm install && npm run dev"
  
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  


volumes:
  postgres_data:
  
    